import { CexProvider } from "components/BridgeL1L2/OtherProviders/Providers/CexProvider";
import { ChaingeProvider } from "components/BridgeL1L2/OtherProviders/Providers/ChaingeProvider";
import { CoinifyProvider } from "components/BridgeL1L2/OtherProviders/Providers/CoinifyProvider";
import { UrlProvider } from "components/BridgeL1L2/OtherProviders/Providers/UrlProvider";
import { BridgedNetwork, FiatMethod, OtherBridgeProvider } from "./types";

export const providers: OtherBridgeProvider[] = [
    {
        label: 'Chainge',
        code: 'chainge',
        isCex: false,
        description: 'Chainge Finance',
        url: 'chainge.io',
        logoUrl: '/bridge-providers/chainge-logo.png',
        supportsCrypto: true,
        supportsFiat: false,
        enabled: true,
        component: ChaingeProvider,
        askOpenInNewTab: false,
        supportsDeposits: true,
        supportsWithdrawals: true,
        supportedInputs: [
            BridgedNetwork.SYS,
            BridgedNetwork.ETH,
            BridgedNetwork.BSC,
            BridgedNetwork.MATIC,
        ],
        supportedOutputs: [
            BridgedNetwork.SYS,
            BridgedNetwork.ETH,
            BridgedNetwork.BSC,
            BridgedNetwork.MATIC,
        ],
        supportedTokens: [
            'ETH',
            'USDT',
            'USDC',
            'BTC',
        ]
    },
    // layerswap
    {
        label: 'Layerswap',
        code: 'layerswap',
        isCex: false,
        description: 'LayerSwap',
        url: 'layerswap.io',
        urlProviderDestination: 'layerswap.io/app',
        logoUrl: '/bridge-providers/layerswap.png',
        supportsCrypto: true,
        supportsFiat: true,
        enabled: true,
        component: UrlProvider,
        askOpenInNewTab: false,
        supportsDeposits: true,
        supportsWithdrawals: true,
        supportedInputs: [
            BridgedNetwork.SYS,
            BridgedNetwork.ETH,
            BridgedNetwork.BSC,
            BridgedNetwork.MATIC,
        ],
        supportedOutputs: [
            BridgedNetwork.SYS,
            BridgedNetwork.ETH,
            BridgedNetwork.BSC,
            BridgedNetwork.MATIC,
        ],
        supportedTokens: [
            'USDC',
        ]
    },
    {
        label: 'Coinify',
        code: 'coinify',
        isCex: false,
        description: 'Coinify',
        url: 'coinify.com',
        logoUrl: '/bridge-providers/coinify-logo.png',
        supportsCrypto: true,
        supportsFiat: true,
        enabled: true,
        component: CoinifyProvider,
        askOpenInNewTab: false,
        supportsDeposits: true,
        supportsWithdrawals: true,
        supportedInputs: [
            FiatMethod.USD,
            FiatMethod.EUR,
            FiatMethod.PLN,
            FiatMethod.JPY,
        ],
        supportedOutputs: [],
        supportedTokens: [
            'SYS',
        ],
    },
    // CEX PROVIDERS
    {
        label: 'Digifinex',
        code: 'digifinex',
        isCex: true,
        description: 'Digifinex',
        url: 'https://www.digifinex.com',
        logoUrl: '/bridge-providers/digifinex.png',
        supportsCrypto: true,
        supportsFiat: true,
        enabled: true,
        component: CexProvider,
        askOpenInNewTab: false,
        supportsDeposits: true,
        supportsWithdrawals: true,
        supportedInputs: [
            FiatMethod.USD,
            FiatMethod.EUR,
            FiatMethod.CNY,
            FiatMethod.PLN,
            FiatMethod.JPY,
        ],
        supportedOutputs: [
            FiatMethod.USD,
            FiatMethod.EUR,
            FiatMethod.CNY,
            FiatMethod.PLN,
            FiatMethod.JPY,
            BridgedNetwork.SYS,
            BridgedNetwork.ETH,
            BridgedNetwork.BSC,
            BridgedNetwork.MATIC,
        ],
        supportedTokens: [
            'SYS',
            'USDT',
            'USDC',

        ],
    },
    // {
    //     label: 'KuCoin',
    //     code: 'kucoin',
    //     isCex: true,
    //     description: 'KuCoin',
    //     url: 'https://www.kucoin.com',
    //     logoUrl: '/providers/icons/kucoin.png',
    //     supportsCrypto: true,
    //     supportsFiat: true,
    //     enabled: false,
    //     component: CexProvider,
    //     askOpenInNewTab: false,
    //     supportsDeposits: true,
    //     supportsWithdrawals: true,
    //     supportedInputs: [
    //         FiatMethod.USD,
    //         FiatMethod.EUR,
    //         FiatMethod.CNY,
    //         FiatMethod.PLN,
    //         FiatMethod.JPY,
    //     ],
    //     supportedOutputs: [
    //         FiatMethod.USD,
    //         FiatMethod.EUR,
    //         FiatMethod.CNY,
    //         FiatMethod.PLN,
    //         FiatMethod.JPY,
    //         BridgedNetwork.SYS,
    //         BridgedNetwork.ETH,
    //         BridgedNetwork.BSC,
    //         BridgedNetwork.MATIC,
    //     ],
    //     supportedTokens: [
    //         'SYS',
    //         'USDT',
    //         'USDC',

    //     ],
    // },
    {
        label: 'MEXC',
        code: 'mexc',
        isCex: true,
        description: 'MEXC',
        url: 'https://www.mexc.com',
        logoUrl: '/providers/icons/mexc.png',
        supportsCrypto: true,
        supportsFiat: true,
        enabled: true,
        component: CexProvider,
        askOpenInNewTab: false,
        supportsDeposits: true,
        supportsWithdrawals: true,
        supportedInputs: [
            FiatMethod.USD,
            FiatMethod.EUR,
            FiatMethod.CNY,
            FiatMethod.PLN,
            FiatMethod.JPY,
        ],
        supportedOutputs: [
            FiatMethod.USD,
            FiatMethod.EUR,
            FiatMethod.CNY,
            FiatMethod.PLN,
            FiatMethod.JPY,
            BridgedNetwork.SYS,
            BridgedNetwork.ETH,
            BridgedNetwork.BSC,
            BridgedNetwork.MATIC,
        ],
        supportedTokens: [
            'SYS',
            'USDT',
            'USDC',

        ],
    },
    {
        label: 'LBank',
        code: 'lbank',
        isCex: true,
        description: 'LBank',
        url: 'https://www.lbank.com',
        logoUrl: '/providers/icons/lbank.png',
        supportsCrypto: true,
        supportsFiat: true,
        enabled: true,
        component: CexProvider,
        askOpenInNewTab: false,
        supportsDeposits: true,
        supportsWithdrawals: true,
        supportedInputs: [
            FiatMethod.USD,
            FiatMethod.EUR,
            FiatMethod.CNY,
            FiatMethod.PLN,
            FiatMethod.JPY,
        ],
        supportedOutputs: [
            FiatMethod.USD,
            FiatMethod.EUR,
            FiatMethod.CNY,
            FiatMethod.PLN,
            FiatMethod.JPY,
            BridgedNetwork.SYS,
            BridgedNetwork.ETH,
            BridgedNetwork.BSC,
            BridgedNetwork.MATIC,
        ],
        supportedTokens: [
            'SYS',
            'USDT',
            'USDC',

        ],
    },
    {
        label: 'BitMart',
        code: 'bitmart',
        isCex: true,
        description: 'BitMart',
        url: 'https://www.bitmart.com',
        logoUrl: '/providers/icons/bitmart.png',
        supportsCrypto: true,
        supportsFiat: true,
        enabled: true,
        component: CexProvider,
        askOpenInNewTab: false,
        supportsDeposits: true,
        supportsWithdrawals: true,
        supportedInputs: [
            FiatMethod.USD,
            FiatMethod.EUR,
            FiatMethod.CNY,
            FiatMethod.PLN,
            FiatMethod.JPY,
        ],
        supportedOutputs: [
            FiatMethod.USD,
            FiatMethod.EUR,
            FiatMethod.CNY,
            FiatMethod.PLN,
            FiatMethod.JPY,
            BridgedNetwork.SYS,
            BridgedNetwork.ETH,
            BridgedNetwork.BSC,
            BridgedNetwork.MATIC,
        ],
        supportedTokens: [
            'SYS',
            'USDT',
            'USDC',

        ],
    },

]
